changelog:
  exclude:
    labels:
      - ignore-for-release
    authors:
      - octocat
  categories:
    - title: ✨ Enhancements
      labels:
        - enhancement
    - title: 🐛 Bug Fixes
      labels:
        - bug
    - title: 🚀 Performance Improvements 
      labels:
        - performance
    - title: 📦 Dependencies
      labels:
        - dependencies
    - title: 📚 Documentation 
      labels:
        - documentation
    - title: Other Changes
      labels:
        - "*"
