name: Create Stable Release

on:
  push:
    tags:
      - v*

permissions:
  contents: write

jobs:
  release:
    name: Release pushed tag
    runs-on: ubuntu-22.04
    steps:
      - name: Create release
        uses: softprops/action-gh-release@v3
        with:
          token: ${{ secrets.GH_RELEASE_PAT }}
          generate_release_notes: true
          make_latest: true
          prerelease: false

