name: Release Main
on:
  pull_request:
    branches: [ "main" ]
  push:
    branches:
      - main
jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    steps:
      - name: Release
        uses: googleapis/release-please-action@v4
        with:
          # target-branch: ${{ github.ref_name }} 
          target-branch: fix/release-please-sections
          token: ${{ secrets.GH_RELEASE_PAT }}
          config-file: .github/release-please-config.main.json
          manifest-file: .github/.release-please-manifest.json
